# Generated by Django 4.1.7 on 2023-05-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
